version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "40e45366-f89a-434e-8209-a86d1d87111f"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: '40e45366-f89a-434e-8209-a86d1d87111f'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      boot40e45366-f89a-434e-8209-a86d1d87111f: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/vagrant/MSc-Kauri/runkauri/kollaps/topology_inforum.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet

  dashboard-40e45366-f89a-434e-8209-a86d1d87111f:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      KOLLAPS_UUID: '40e45366-f89a-434e-8209-a86d1d87111f'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet
      - outside

  server1-40e45366-f89a-434e-8209-a86d1d87111f:
    image: kauri
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['bls','5','5','1','10','20','500']
    hostname: server1
    labels:
      40e45366-f89a-434e-8209-a86d1d87111f: "true"
    deploy:
      replicas: 31
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '40e45366-f89a-434e-8209-a86d1d87111f'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

networks:
  KollapsNet:
    external:
      name: kauri_network
  outside:
    driver: overlay

