version: "3.3"
services:
  server1-becd9691-b958-47c3-9ac3-688ca48fb6d6:
    image: kauri
    entrypoint: ["/bin/bash", "/server.sh"]
    command: ['bls','2','1','1','10','100','500']
    hostname: server1
    cap_add:
      - NET_ADMIN
    labels:
      becd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
    deploy:
      replicas: 7
      endpoint_mode: dnsrr
    environment:
      KAURI_UUID: 'becd9691-b958-47c3-9ac3-688ca48fb6d6'
    networks:
      - KauriNet

  server2-becd9691-b958-47c3-9ac3-688ca48fb6d6:
    image: kauri
    entrypoint: ["/bin/bash", "/server.sh"]
    command: ['bls','2','1','1','10','100','500']
    hostname: server2
    cap_add:
      - NET_ADMIN
    labels:
      becd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
    deploy:
      replicas: 8
      endpoint_mode: dnsrr
    environment:
      KAURI_UUID: 'becd9691-b958-47c3-9ac3-688ca48fb6d6'
    networks:
      - KauriNet

  # client-becd9691-b958-47c3-9ac3-688ca48fb6d6:
  #   image: kauri
  #   entrypoint: ["/bin/bash", "/client.sh"]
  #   command: ['bls','2','1','1','10','100','500']
  #   hostname: client
  #   cap_add:
  #     - NET_ADMIN
  #   labels:
  #     becd9691-b958-47c3-9ac3-688ca48fb6d6: "true"
  #   deploy:
  #     replicas: 1
  #     endpoint_mode: dnsrr
  #   environment:
  #     KAURI_UUID: 'becd9691-b958-47c3-9ac3-688ca48fb6d6'
  #   networks:
  #     - KauriNet

networks:
  KauriNet:
    external:
      name: kauri_network
  outside:
    driver: overlay
