#include "hotstuff/activation_readiness_wire.h"

#include <algorithm>
#include <limits>
#include <new>
#include <stdexcept>

#include "detail/canonical_wire_codec.h"

namespace hotstuff
{
namespace
{
const std::string kObservationDomain = "kauri-adaptive-v3-activation-ready-observation-v1";
const std::string kIdentityDomain = "kauri-adaptive-v3-activation-ready-identity-v1";
const std::string kCertificateDomain = "kauri-adaptive-v3-activation-readiness-certificate-v1";
const std::string kAckDomain = "kauri-adaptive-v3-activation-readiness-ack-v1";
const std::string kCertificateDigestDomain = "kauri-adaptive-v3-activation-readiness-certificate-digest-v1";
const std::string kAckPayloadDigestDomain = "kauri-adaptive-v3-activation-readiness-ack-payload-digest-v1";
constexpr std::uint8_t kCanonicalFlags = 0;
constexpr std::size_t kSignatureBytes = bls::G2Element::SIZE;
struct WireFailure { ActivationReadinessWireError error; };
using Writer = detail::CanonicalWireWriter;
using Reader = detail::CanonicalWireReader<WireFailure, ActivationReadinessWireError>;

bool zero(const uint256_t &value) noexcept { return value == uint256_t{}; }
bool valid_limits(const ActivationReadinessWireLimits &limits) noexcept { return limits.maximum_payload_bytes != 0 && limits.maximum_members != 0; }
bool valid_configuration(const ConfigurationId &value) noexcept { return value.epoch_digest != uint256_t{}; }
bool canonical_generation(std::uint32_t epoch, std::uint64_t generation,
                          std::uint32_t ordinal) noexcept {
    const auto expected = checked_activation_generation(epoch, ordinal);
    return expected.has_value() && *expected == generation;
}
bool valid_predecessor_generation(std::uint32_t epoch,
                                  std::uint64_t generation) noexcept {
    if (generation == 0) return false;
    const auto packed = generation - 1;
    const auto ordinal = static_cast<std::uint32_t>(packed);
    return canonical_generation(epoch, generation, ordinal);
}
bool valid_identity(const ActivationReadyIdentityV1 &v) noexcept {
    if (v.schema_version != kActivationReadinessSchemaVersionV1 || zero(v.membership_digest) ||
        !valid_configuration(v.predecessor_boundary_configuration) || !valid_configuration(v.successor_configuration) ||
        !valid_predecessor_generation(v.predecessor_boundary_configuration.epoch_number,
                                      v.predecessor_boundary_generation) ||
        !canonical_generation(v.successor_configuration.epoch_number,
                              v.successor_activation_generation, 0) ||
        v.predecessor_boundary_configuration.epoch_number == std::numeric_limits<std::uint32_t>::max() ||
        v.successor_configuration.epoch_number != v.predecessor_boundary_configuration.epoch_number + 1 ||
        v.successor_configuration.tree_id != 0 || zero(v.command_payload_digest) ||
        v.command_block_height == 0 || zero(v.command_block_hash) || v.activation_delay_blocks == 0 ||
        v.command_block_height > std::numeric_limits<std::uint64_t>::max() - v.activation_delay_blocks ||
        v.activation_height != v.command_block_height + v.activation_delay_blocks || zero(v.activation_boundary_block_hash) ||
        v.predecessor_boundary_configuration.epoch_digest == v.successor_configuration.epoch_digest) return false;
    return true;
}
void encode_configuration(Writer &w, const ConfigurationId &v) { w.integer(v.epoch_number); w.integer(v.tree_id); w.digest(v.epoch_digest, "activation readiness configuration digest is not 32 bytes"); }
ConfigurationId decode_configuration(Reader &r) { ConfigurationId v; v.epoch_number=r.integer<std::uint32_t>(); v.tree_id=r.integer<std::uint32_t>(); v.epoch_digest=r.digest(); return v; }
void encode_identity(Writer &w, const ActivationReadyIdentityV1 &v) {
    w.integer(v.schema_version); w.digest(v.membership_digest, "activation readiness membership digest is not 32 bytes");
    encode_configuration(w,v.predecessor_boundary_configuration); w.integer(v.predecessor_boundary_generation);
    encode_configuration(w,v.successor_configuration); w.integer(v.successor_activation_generation);
    w.digest(v.command_payload_digest,"activation readiness command digest is not 32 bytes"); w.integer(v.command_block_height);
    w.digest(v.command_block_hash,"activation readiness command hash is not 32 bytes"); w.integer(v.activation_delay_blocks); w.integer(v.activation_height);
    w.digest(v.activation_boundary_block_hash,"activation readiness boundary hash is not 32 bytes");
}
ActivationReadyIdentityV1 decode_identity(Reader &r) { ActivationReadyIdentityV1 v; v.schema_version=r.integer<std::uint32_t>(); v.membership_digest=r.digest(); v.predecessor_boundary_configuration=decode_configuration(r); v.predecessor_boundary_generation=r.integer<std::uint64_t>(); v.successor_configuration=decode_configuration(r); v.successor_activation_generation=r.integer<std::uint64_t>(); v.command_payload_digest=r.digest(); v.command_block_height=r.integer<std::uint64_t>(); v.command_block_hash=r.digest(); v.activation_delay_blocks=r.integer<std::uint64_t>(); v.activation_height=r.integer<std::uint64_t>(); v.activation_boundary_block_hash=r.digest(); return v; }
bool valid_observation(const ActivationReadyObservationV1 &v) noexcept { return valid_identity(v.identity) && v.signer_source_sequence != 0 && v.vote_fence_engaged; }
void encode_observation_without_domain(Writer &w, const ActivationReadyObservationV1 &v) { encode_identity(w,v.identity); w.integer(v.signer_replica_id); w.integer(v.signer_source_sequence); w.integer(v.signer_monotonic_raw_ns); w.integer(static_cast<std::uint8_t>(v.vote_fence_engaged ? 1 : 0)); w.bytes(v.signature.to_bytes()); }
ActivationReadyObservationV1 decode_observation_without_domain(Reader &r) { ActivationReadyObservationV1 v; v.identity=decode_identity(r); v.signer_replica_id=r.integer<ReplicaID>(); v.signer_source_sequence=r.integer<std::uint64_t>(); v.signer_monotonic_raw_ns=r.integer<std::uint64_t>(); v.vote_fence_engaged=r.integer<std::uint8_t>() == 1; const auto sig=r.bytes(kSignatureBytes); v.signature.from_bytes(sig); return v; }
bool sorted_unique(const std::vector<ActivationReadyObservationV1> &v) noexcept { for (std::size_t i=1;i<v.size();++i) if (v[i-1].signer_replica_id >= v[i].signer_replica_id) return false; return true; }
bool valid_certificate(const ActivationReadinessCertificateV1 &v) noexcept { if (v.schema_version != kActivationReadinessSchemaVersionV1 || !valid_identity(v.identity) || v.observations.empty() || !sorted_unique(v.observations) || zero(v.certificate_digest)) return false; for (const auto &o:v.observations) if (!valid_observation(o) || o.identity != v.identity) return false; return true; }
bool valid_ack(const ActivationReadinessAckV1 &v) noexcept { return v.schema_version == kActivationReadinessSchemaVersionV1 && (v.acknowledged_opcode == MsgActivationReadyObservation::opcode || v.acknowledged_opcode == MsgActivationReadinessCertificate::opcode) && valid_identity(v.identity) && !zero(v.certificate_digest) && !zero(v.payload_digest) && (v.disposition == ActivationReadinessAckDisposition::positive || v.disposition == ActivationReadinessAckDisposition::permanent_rejection); }
bool canonical_members(const std::vector<std::pair<ReplicaID, PubKeyBLS>> &members) noexcept { for (std::size_t i = 1; i < members.size(); ++i) if (members[i - 1].first >= members[i].first) return false; return !members.empty(); }
template<typename T> ActivationReadinessDecodeResult<T> reject(ActivationReadinessWireError e) noexcept { return {e,std::nullopt}; }
[[noreturn]] void encoding_error() { throw std::invalid_argument("activation readiness wire value is not canonical"); }
}

bool ActivationReadyIdentityV1::operator==(const ActivationReadyIdentityV1 &o) const noexcept { return schema_version==o.schema_version && membership_digest==o.membership_digest && predecessor_boundary_configuration==o.predecessor_boundary_configuration && predecessor_boundary_generation==o.predecessor_boundary_generation && successor_configuration==o.successor_configuration && successor_activation_generation==o.successor_activation_generation && command_payload_digest==o.command_payload_digest && command_block_height==o.command_block_height && command_block_hash==o.command_block_hash && activation_delay_blocks==o.activation_delay_blocks && activation_height==o.activation_height && activation_boundary_block_hash==o.activation_boundary_block_hash; }
bool ActivationReadyIdentityV1::operator!=(const ActivationReadyIdentityV1 &o) const noexcept { return !(*this==o); }
const std::string &activation_ready_observation_domain() noexcept { return kObservationDomain; }
const std::string &activation_ready_identity_domain() noexcept { return kIdentityDomain; }
const std::string &activation_readiness_certificate_domain() noexcept { return kCertificateDomain; }
const std::string &activation_readiness_ack_domain() noexcept { return kAckDomain; }
uint256_t canonical_activation_readiness_membership_digest(const std::vector<std::pair<ReplicaID, PubKeyBLS>> &members) { if (!canonical_members(members)) throw std::invalid_argument("activation readiness membership is not canonical"); Writer w; w.domain("kauri-adaptive-v3-activation-readiness-membership-v1"); w.integer(static_cast<std::uint32_t>(members.size())); for (const auto &member : members) { w.integer(member.first); w.bytes(member.second.to_bytes()); } return DataStream(std::move(w).finish()).get_hash(); }
uint256_t activation_ready_observation_digest(const ActivationReadyObservationV1 &v) { if (!valid_observation(v)) encoding_error(); Writer w; w.domain(kObservationDomain); encode_identity(w,v.identity); w.integer(v.signer_replica_id); w.integer(v.signer_source_sequence); w.integer(v.signer_monotonic_raw_ns); w.integer(static_cast<std::uint8_t>(1)); return DataStream(std::move(w).finish()).get_hash(); }
uint256_t activation_readiness_certificate_digest(const ActivationReadinessCertificateV1 &v) { if (v.schema_version != kActivationReadinessSchemaVersionV1 || !valid_identity(v.identity) || v.observations.empty() || !sorted_unique(v.observations)) encoding_error(); Writer w; w.domain(kCertificateDigestDomain); w.integer(v.schema_version); encode_identity(w,v.identity); w.integer(static_cast<std::uint32_t>(v.observations.size())); for (const auto &o:v.observations) encode_observation_without_domain(w,o); return DataStream(std::move(w).finish()).get_hash(); }
uint256_t activation_readiness_ack_payload_digest(opcode_t opcode, const bytearray_t &payload) { if (opcode != MsgActivationReadyObservation::opcode && opcode != MsgActivationReadinessCertificate::opcode) throw std::invalid_argument("unsupported activation readiness acknowledgement opcode"); Writer w; w.domain(kAckPayloadDigestDomain); w.integer(opcode); w.integer(static_cast<std::uint64_t>(payload.size())); w.bytes(payload); return DataStream(std::move(w).finish()).get_hash(); }
ActivationReadyObservationV1 sign_activation_ready_observation(ActivationReadyIdentityV1 identity, ReplicaID id, std::uint64_t seq, std::uint64_t clock, const PrivKeyBLS &key) { ActivationReadyObservationV1 v; v.identity=std::move(identity); v.signer_replica_id=id; v.signer_source_sequence=seq; v.signer_monotonic_raw_ns=clock; v.vote_fence_engaged=true; v.signature.sign(activation_ready_observation_digest(v),key); return v; }
ActivationReadinessCertificateV1 make_activation_readiness_certificate(ActivationReadyIdentityV1 identity, std::vector<ActivationReadyObservationV1> observations) { ActivationReadinessCertificateV1 v; v.identity=std::move(identity); v.observations=std::move(observations); v.certificate_digest=activation_readiness_certificate_digest(v); if (!valid_certificate(v)) encoding_error(); return v; }
bytearray_t encode_activation_ready_identity_v1(const ActivationReadyIdentityV1 &v,const ActivationReadinessWireLimits &l) { if(!valid_limits(l)||!valid_identity(v))encoding_error();Writer w(l.maximum_payload_bytes,"activation readiness identity exceeds byte limit");w.domain(kIdentityDomain);w.integer(kCanonicalFlags);encode_identity(w,v);return std::move(w).finish(); }
ActivationReadyIdentityDecodeResult decode_activation_ready_identity_v1(const bytearray_t&p,const ActivationReadinessWireLimits&l) noexcept { try {if(!valid_limits(l))return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::invalid_limits);if(p.size()>l.maximum_payload_bytes)return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::payload_too_large);Reader r(p,ActivationReadinessWireError::truncated);r.domain(kIdentityDomain,ActivationReadinessWireError::invalid_domain);if(r.integer<std::uint8_t>()!=kCanonicalFlags)return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::noncanonical_encoding);auto v=decode_identity(r);if(!valid_identity(v))return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::invalid_identity);if(!r.empty())return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::trailing_bytes);if(encode_activation_ready_identity_v1(v,l)!=p)return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::noncanonical_encoding);return {ActivationReadinessWireError::none,std::move(v)};}catch(const WireFailure&e){return reject<ActivationReadyIdentityV1>(e.error);}catch(const std::bad_alloc&){return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::allocation_failure);}catch(...){return reject<ActivationReadyIdentityV1>(ActivationReadinessWireError::internal_failure);} }
bytearray_t encode_activation_ready_observation(const ActivationReadyObservationV1 &v,const ActivationReadinessWireLimits &l) { if(!valid_limits(l)||!valid_observation(v)) encoding_error(); Writer w(l.maximum_payload_bytes,"activation readiness observation exceeds byte limit"); w.domain(kObservationDomain); w.integer(kCanonicalFlags); encode_observation_without_domain(w,v); return std::move(w).finish(); }
ActivationReadyObservationDecodeResult decode_activation_ready_observation(const bytearray_t&p,const ActivationReadinessWireLimits&l) noexcept { try { if(!valid_limits(l)) return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::invalid_limits); if(p.size()>l.maximum_payload_bytes)return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::payload_too_large); Reader r(p,ActivationReadinessWireError::truncated); r.domain(kObservationDomain,ActivationReadinessWireError::invalid_domain); if(r.integer<std::uint8_t>()!=kCanonicalFlags)return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::noncanonical_encoding); auto v=decode_observation_without_domain(r); if(!valid_observation(v))return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::invalid_observation); if(!r.empty())return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::trailing_bytes); if(encode_activation_ready_observation(v,l)!=p)return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::noncanonical_encoding); return {ActivationReadinessWireError::none,std::move(v)}; } catch(const WireFailure&e){return reject<ActivationReadyObservationV1>(e.error);}catch(const std::bad_alloc&){return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::allocation_failure);}catch(...){return reject<ActivationReadyObservationV1>(ActivationReadinessWireError::internal_failure);} }
bytearray_t encode_activation_readiness_certificate(const ActivationReadinessCertificateV1 &v,const ActivationReadinessWireLimits &l) { if(!valid_limits(l)||v.observations.size()>l.maximum_members||!valid_certificate(v)||v.certificate_digest!=activation_readiness_certificate_digest(v)) encoding_error(); Writer w(l.maximum_payload_bytes,"activation readiness certificate exceeds byte limit"); w.domain(kCertificateDomain); w.integer(kCanonicalFlags); w.integer(v.schema_version); encode_identity(w,v.identity); w.integer(static_cast<std::uint32_t>(v.observations.size())); for(const auto&o:v.observations)encode_observation_without_domain(w,o); w.digest(v.certificate_digest,"activation readiness certificate digest is not 32 bytes"); return std::move(w).finish(); }
ActivationReadinessCertificateDecodeResult decode_activation_readiness_certificate(const bytearray_t&p,const ActivationReadinessWireLimits&l) noexcept { try { if(!valid_limits(l))return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::invalid_limits);if(p.size()>l.maximum_payload_bytes)return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::payload_too_large); Reader r(p,ActivationReadinessWireError::truncated);r.domain(kCertificateDomain,ActivationReadinessWireError::invalid_domain);if(r.integer<std::uint8_t>()!=kCanonicalFlags)return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::noncanonical_encoding);ActivationReadinessCertificateV1 v;v.schema_version=r.integer<std::uint32_t>();v.identity=decode_identity(r);const auto n=r.integer<std::uint32_t>();if(n==0||n>l.maximum_members)return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::too_many_observations);v.observations.reserve(n);for(std::uint32_t i=0;i<n;++i)v.observations.push_back(decode_observation_without_domain(r));v.certificate_digest=r.digest();if(!valid_certificate(v)||v.certificate_digest!=activation_readiness_certificate_digest(v))return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::invalid_certificate);if(!r.empty())return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::trailing_bytes);if(encode_activation_readiness_certificate(v,l)!=p)return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::noncanonical_encoding);return {ActivationReadinessWireError::none,std::move(v)};}catch(const WireFailure&e){return reject<ActivationReadinessCertificateV1>(e.error);}catch(const std::bad_alloc&){return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::allocation_failure);}catch(...){return reject<ActivationReadinessCertificateV1>(ActivationReadinessWireError::internal_failure);} }
bytearray_t encode_activation_readiness_ack(const ActivationReadinessAckV1 &v,const ActivationReadinessWireLimits&l) { if(!valid_limits(l)||!valid_ack(v))encoding_error();Writer w(l.maximum_payload_bytes,"activation readiness acknowledgement exceeds byte limit");w.domain(kAckDomain);w.integer(kCanonicalFlags);w.integer(v.schema_version);w.integer(v.acknowledged_opcode);w.integer(v.recipient_replica_id);encode_identity(w,v.identity);w.digest(v.certificate_digest,"activation readiness certificate digest is not 32 bytes");w.digest(v.payload_digest,"activation readiness payload digest is not 32 bytes");w.integer(static_cast<std::uint8_t>(v.disposition));return std::move(w).finish(); }
ActivationReadinessAckDecodeResult decode_activation_readiness_ack(const bytearray_t&p,const ActivationReadinessWireLimits&l) noexcept { try {if(!valid_limits(l))return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::invalid_limits);if(p.size()>l.maximum_payload_bytes)return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::payload_too_large);Reader r(p,ActivationReadinessWireError::truncated);r.domain(kAckDomain,ActivationReadinessWireError::invalid_domain);if(r.integer<std::uint8_t>()!=kCanonicalFlags)return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::noncanonical_encoding);ActivationReadinessAckV1 v;v.schema_version=r.integer<std::uint32_t>();v.acknowledged_opcode=r.integer<opcode_t>();v.recipient_replica_id=r.integer<ReplicaID>();v.identity=decode_identity(r);v.certificate_digest=r.digest();v.payload_digest=r.digest();v.disposition=static_cast<ActivationReadinessAckDisposition>(r.integer<std::uint8_t>());if(!valid_ack(v))return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::invalid_acknowledgement);if(!r.empty())return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::trailing_bytes);if(encode_activation_readiness_ack(v,l)!=p)return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::noncanonical_encoding);return {ActivationReadinessWireError::none,std::move(v)};}catch(const WireFailure&e){return reject<ActivationReadinessAckV1>(e.error);}catch(const std::bad_alloc&){return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::allocation_failure);}catch(...){return reject<ActivationReadinessAckV1>(ActivationReadinessWireError::internal_failure);} }
bool verify_activation_ready_observation(const ActivationReadyObservationV1 &v,const PubKeyBLS &key) noexcept { try{return valid_observation(v)&&v.signature.verify(activation_ready_observation_digest(v),key);}catch(...){return false;} }
bool verify_activation_readiness_certificate(const ActivationReadinessCertificateV1 &v,const ActivationReadyIdentityV1 &expected,const uint256_t &digest,const std::vector<std::pair<ReplicaID,PubKeyBLS>>&members) noexcept { try { const auto n = members.size(); if (n < 4 || (n - 1) % 3 != 0 || !canonical_members(members)) return false; const auto f = (n - 1) / 3; const auto quorum = 2 * f + 1; if(!valid_certificate(v)||v.identity!=expected||v.identity.membership_digest!=digest||digest!=canonical_activation_readiness_membership_digest(members)||v.certificate_digest!=activation_readiness_certificate_digest(v)||v.observations.size()<quorum)return false;for(const auto&o:v.observations){auto it=std::lower_bound(members.begin(),members.end(),o.signer_replica_id,[](const auto &m,ReplicaID id){return m.first<id;});if(it==members.end()||it->first!=o.signer_replica_id||!verify_activation_ready_observation(o,it->second))return false;}return true;}catch(...){return false;} }
const opcode_t MsgActivationReadyObservation::opcode; const opcode_t MsgActivationReadinessCertificate::opcode; const opcode_t MsgActivationReadinessAck::opcode;
MsgActivationReadyObservation::MsgActivationReadyObservation(const ActivationReadyObservationV1&v,const ActivationReadinessWireLimits&l):serialized(encode_activation_ready_observation(v,l)){} MsgActivationReadyObservation::MsgActivationReadyObservation(DataStream&&v):serialized(std::move(v)){}
MsgActivationReadinessCertificate::MsgActivationReadinessCertificate(const ActivationReadinessCertificateV1&v,const ActivationReadinessWireLimits&l):serialized(encode_activation_readiness_certificate(v,l)){} MsgActivationReadinessCertificate::MsgActivationReadinessCertificate(DataStream&&v):serialized(std::move(v)){}
MsgActivationReadinessAck::MsgActivationReadinessAck(const ActivationReadinessAckV1&v,const ActivationReadinessWireLimits&l):serialized(encode_activation_readiness_ack(v,l)){} MsgActivationReadinessAck::MsgActivationReadinessAck(DataStream&&v):serialized(std::move(v)){}
} // namespace hotstuff
